### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by goksunozhan** [rslavin/slack2discord#10]
Dear @rslavin I'm getting this error randomly while importing some json files. Could you please help?
```
TypeError: argument of type 'NoneType' is not iterable
The above exception was the direct cause of the following exception:
```

**Comment by rslavin** [comment]
@feha can you take a look at this? It seems like there is a problem if one of the json files are empty.

**Comment by feha** [comment]
@rslavin Sure. And thanks for the further clarification on how to reproduce too, as the exception appears cut out of OP's quote for me.
