### ISSUE TITLE
Process failed when there's no slack2discord_users.json present.

### ISSUE THREAD

**Issue by ananttheant** [rslavin/slack2discord#12]
It'll be a better idea to check if the _slack2discord_users.json_ file exists or not.

If the file doesn't exist, then do:
- [ ] Don't check for the nicks (nickname - user) user mapping.
- [ ] Update the [README.md](https://github.com/rslavin/slack2discord/blob/master/README.md), adding a note that you have to either add the mapping for nicknames or an empty _slack2discord_users.json_ file.

**Comment by ananttheant** [comment]
Please refer to: ananttheant:ananttheant-Hotfix-missing-slack2discord_users.json

**Comment by ananttheant** [comment]
Hotfix: [Readme update](https://github.com/rslavin/slack2discord/pull/13)

**Comment by rslavin** [comment]
Fixed with #11
