### ISSUE TITLE
Don't require slack2discord_users.json

### ISSUE THREAD

**Issue by usarid** [rslavin/slack2discord#14]
Right now, unless one knows they have to add a `slack2discord_users.json` file (even one just containing `{}`) to the Slack export directory, the bot fails quite mysteriously, claiming the path isn't a valid Slack export directory. 

The suggestion is to not require such a file: use it if it's there, otherwise behave as if it were there and contained `{}`.

If that's not doable now, then perhaps just document the need to add such a file in the README.

**Comment by rslavin** [comment]
@feha can I bug you to take a look at this since this is part of your additions? Ideally, if `slack2discord_users.json` does not exist, the bot should proceed as though there are no users to import.

**Comment by feha** [comment]
Sure. Busy today, but can probably look at it tomorrow or soon thereafter :)

**Comment by rslavin** [comment]
No problem! I appreciate your contributions. :)

**Comment by feha** [comment]
Glanced quickly at the repo through the browser, and as a temporary workaround for @usarid I am fairly sure the issue lies in the import_all command's 'force_all' parameter, meaning _the other commands should still work fine even without the file._ Though as I said this was just a quick check without access to tests, so might still be wrong :p

**Comment by feha** [comment]
@rslavin I made a pull request that _should_ fix this issue, now :)

edit: of note, it now actually _does_ query user about something more than the bot-token (so might want to update the docs, although it's so minor might not be worth it). In specific, it now queries user (in the console - not discord) whether to ignore missing files ("y"/"yes"), or abort the command.

**Comment by rslavin** [comment]
Thanks @feha , you're the best!

**Comment by usarid** [comment]
Thank you!
