### ISSUE TITLE
Docs are confusing for poor little me

### ISSUE THREAD

**Issue by Brade** [rslavin/slack2discord#15]
I'm a senior programmer who is somehow struggling with this library (which I greatly need to work BTW). I got it to accept my bot token, then typed the "!import_all ~/path" command in my terminal (is that the right place?) but it just sits there. Not sure what I'm doing wrong =[

**Comment by rslavin** [comment]
You should invoke these commands directly in Discord after your bot is running and has joined the server.

**Comment by Brade** [comment]
Ha thanks, it is working now. Another thing I noticed: I had to put a "slack2discord_users.json" file in my exported slack directory, even if I left it blank. Without that file, the process would not start.

**Comment by rslavin** [comment]
Yes, that's actually an issues that is currently being addressed in #14 . It should be fixed soon. :)
